feat(thanos): adding initial plugin
cloudoperators/greenhouse-extensions pull request #183
Opened 2024-06-28 11:37 UTC by viennaa

---

## Pull Request Details

currently the plugin deploys the Query only. Compactor is already in but not yet tested/activated

## Breaking Changes

None

## Issues Fixed

None

## Other Relevant Information

2024-07-11 07:36 UTC, richardtief requested changes
I really like that! Thanks for going to the effort of making Thanos pluggable. Some NITs below.

2024-07-11 07:36 UTC, richardtief commented on thanos/README.md
> +* thanos-sidecar enabled in Prometheus (usually with [Prometheus Operator](https://prometheus-operator.dev/))
Pointing to the ThanosSpec directly.
```suggestion
* thanos-sidecar enabled in Prometheus (usually with [Prometheus Operator](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.ThanosSpec))
```

2024-07-11 07:36 UTC, richardtief commented on thanos/README.md
> +To run thanos you need object store credentials. Choose a provider and add the credentials into a secret. The [Thanos documentation](https://thanos.io/tip/thanos/storage.md/) provides a great overvie
```suggestion
To run Thanos, you need object storage credentials. Get the credentials of your provider and add them to a Kubernetes Secret. The [Thanos documentation](https://thanos.io/tip/thanos/storage.md/) provides a great overview on the different supported store types.
```

2024-07-11 07:36 UTC, richardtief commented on thanos/README.md
> +Prometheus in kube-monitoring needs to be altered to have a sidecar and ship metrics to the new object store too. You have to provide the secret you've just created to the (most likely already existi
```suggestion
Prometheus in kube-monitoring needs to be altered to have a sidecar and ship metrics to the new object store too. You have to provide the Secret you've just created to the (most likely already existing) kube-monitoring plugin. Add this:
```

2024-07-11 07:36 UTC, richardtief commented on thanos/README.md
> +```
```suggestion
```yaml
```

2024-07-11 07:36 UTC, richardtief commented on thanos/README.md
> +By default Thanos Query would check for a service `prometheus-operated` in the same namespace with this GRPC port to be available `10901`. The cli option looks like this and is configured in the Plug
Nice!

2024-07-11 07:36 UTC, richardtief commented on thanos/charts/values.yaml
> +## kube-prometheus-stack configuration scoped to kube-monitoring
```suggestion
```

2024-07-11 07:36 UTC, richardtief commented on thanos/charts/templates/compactor.yaml
> +        - --retention.resolution-1h={{ default "157680000s" .Values.thanos.compactor.retentionResolution1h }}
We should probably mention this in the readme, as it affects the cost of object storage quite a bit.

2024-07-16 07:25 UTC, richardtief commented
Please rebase onto main and add the [codeowners](https://github.com/cloudoperators/greenhouse-extensions/blob/39697246d1146452fe8024032312c189248f3703/.github/CODEOWNERS) team observability to the plugin.

2024-07-16 14:59 UTC, IvoGoman commented
The `plugin.yaml` have been renamed to `plugindefinition.yaml` across the PluginDefinitions on the main branch. Following this naming scheme is important for our CI to pick the definition up.

2024-07-24 13:40 UTC, viennaa commented
CODEOWNERS added and plugin.yaml renamed

2024-07-24 18:19 UTC, richardtief approved these changes

2024-07-25 07:29 UTC, IvoGoman approved these changes

2024-07-25 07:38 UTC, merged