Add integration tests for kube-monitoring components
cloudoperators/greenhouse-extensions pull request #236
Opened 2024-07-22 11:46 UTC by ibakshay

This pull request adds integration tests for the kube-monitoring components. The tests include checking the connectivity to the kube-monitoring-prometheus, kube-monitoring-state-metrics, and kube-monitoring-node-exporter services. The tests also verify the setup of the kube-monitoring-operator components, the creation of the persistent volume, the presence of the kube-monitoring resource of type 'Prometheus', and the creation of the required CRDs for kube-monitoring.

Fixes cloudoperators/greenhouse-extensions#217
deponds on https://github.com/cloudoperators/greenhouse-extensions/pull/237

2024-07-25 12:28 UTC, richardtief requested changes
Marvelous, I really like it! I've left a few comments. Especially with the naming of the resources, there can be potential problems later if you install the kube-monitoring plugin multiple times, e.g. to get just one more Prometheus. 

I have seen that your Git client is not handling newlines correctly. You can find some hints here: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

2024-07-25 12:28 UTC, richardtief commented on kube-monitoring/charts/templates/tests/test-permissions.yaml
> +  name: object-reader
```suggestion
  name: {{ .Release.Name }}-test
```

2024-07-25 12:28 UTC, richardtief commented on kube-monitoring/charts/templates/tests/test-permissions.yaml
> +    name: integration-test
```suggestion
    name: {{ .Release.Name }}-test
```

2024-07-25 13:14 UTC, ibakshay commented on kube-monitoring/charts/templates/tests/test-kube-monitoring-config.yaml
> +    "helm.sh/hook": test
Very good finding. We only need this annotation for the pods that are running the integration tests. We do not need this annotation for other manifests like `configmaps`, `serviceaccounts`, `rolebinding` and so on. These resources will be already created during the `helm install/upgrade <deployment name>` command if these annotations are not present.

2024-07-25 13:23 UTC, ibakshay commented on kube-monitoring/charts/templates/tests/test-kube-monitoring-config.yaml
> +    "helm.sh/hook": test
The resources without the `helm.sg/hook: test` annotation  won't be cleaned up after the `helm test` has been executed. Is that fine from your perspective?

2024-07-25 14:22 UTC, ibakshay commented on kube-monitoring/charts/templates/tests/test-kube-monitoring-config.yaml
> +    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded" # this annotation is used to delete the test pod after the test is successful
I have removed the comments in https://github.com/cloudoperators/greenhouse-extensions/pull/236/commits/8dba9e8ff4e32104df23caebd69630060e5e2d6a commit.

2024-07-25 14:23 UTC, ibakshay commented on kube-monitoring/charts/templates/tests/test-kube-monitoring.yaml
> +    type: integration-test-test
great insight. I have added the common lablels to every resource in this commit https://github.com/cloudoperators/greenhouse-extensions/pull/236/commits/8dba9e8ff4e32104df23caebd69630060e5e2d6a.

2024-07-25 14:24 UTC, ibakshay commented on kube-monitoring/charts/templates/tests/test-kube-monitoring.yaml
> +    - name: bats-test
fixed in this commit https://github.com/cloudoperators/greenhouse-extensions/pull/236/commits/8dba9e8ff4e32104df23caebd69630060e5e2d6a.

2024-07-25 14:24 UTC, ibakshay commented on kube-monitoring/charts/templates/tests/test-kube-monitoring.yaml
> +    type: integration-test-test
fixed in this commit https://github.com/cloudoperators/greenhouse-extensions/pull/236/commits/8dba9e8ff4e32104df23caebd69630060e5e2d6a.

2024-07-25 14:38 UTC, richardtief commented on kube-monitoring/charts/templates/tests/test-kube-monitoring-config.yaml
> +    "helm.sh/hook": test
Ok, then I would leave it as it is. It's even worse if the permissions are lying around, which is not the best security we can offer.

2024-07-26 07:37 UTC, richardtief requested changes
Two nits before we merge: 

1. newlines are still not added at the end of some files. Git needs them to render the diffs correctly. Could you please add them?
2. commented below.

2024-07-26 07:37 UTC, richardtief commented on kube-monitoring/charts/templates/tests/test-permissions.yaml
> +---
The last three hyphens are not required.
```suggestion
```

2024-07-26 07:55 UTC, ibakshay commented
> Two nits before we merge:
> 
> 1. newlines are still not added at the end of some files. Git needs them to render the diffs correctly. Could you please add them? To always have them: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
> 2. commented below.

I have configured by text editor to add new lines at the end of file automatically now :) Thank you for the hint!

2024-07-26 08:03 UTC, richardtief approved these changes
Thanks, let's ship it!

2024-07-26 08:04 UTC, merged