feat(alerts):
cloudoperators/greenhouse-extensions pull request #286
Opened 2024-08-08 15:06 UTC by TilmanHaupt

predefined filters are now passed via props

2024-08-09 06:18 UTC, andypf approved these changes
LGTM

2024-09-04 08:24 UTC, ArtieReus requested changes

2024-09-04 08:24 UTC, ArtieReus commented on alerts/README.md
> -| Name                    | Description
please move the readme or this section to the ui folder

2024-09-04 13:14 UTC, ArtieReus approved these changes
lgtm

2024-09-04 13:15 UTC, merged