[opentelemetry] add testing for plugin
cloudoperators/greenhouse-extensions pull request #340
Opened 2024-08-22 07:25 UTC by timojohlo

## Pull Request Details

- added basic chart testing for core components

## References
[[opentelemetry] make opentelemetry plugin production-ready](https://github.com/cloudoperators/greenhouse-extensions/issues/244)

2024-08-22 08:03 UTC, viennaa requested changes
Thanks for adding the basic tests here, this is needed!

Some small things to change are inline.

2024-08-22 08:03 UTC, viennaa commented on opentelemetry/chart/templates/tests/test-opentelemetry.yaml
> +apiVersion: v1
```suggestion
{{- if .Values.testFramework.enabled -}}
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
```
See first comment and add to other files too.

2024-08-22 08:03 UTC, viennaa commented on opentelemetry/chart/templates/tests/test-permissions.yaml
> +    verbs: ["get", "list"]
I don't see any Prometheus related tests above.

2024-08-22 09:35 UTC, viennaa approved these changes
Thanks, let it test.

2024-08-22 10:25 UTC, IvoGoman requested changes

2024-08-22 10:25 UTC, IvoGoman commented on .github/licenserc.yaml
> +    - 'opentelemetry/chart/templates/tests/**' # ignore the license for the tests of the opentelemetry chart
I guess we need want to ignore this for all tests? Then let's do `**/templates/tests/**` instead of needing to add each chart individually.

2024-08-23 14:04 UTC, IvoGoman commented on .github/licenserc.yaml
> +    - 'opentelemetry/chart/templates/tests/**' # ignore the license for the tests of the opentelemetry chart
The underlying issue has been tracked by @timojohlo here: https://github.com/cloudoperators/greenhouse-extensions/issues/347

2024-08-23 14:04 UTC, IvoGoman approved these changes

2024-08-23 14:05 UTC, merged