feat(heureka): Edit service owners
cloudoperators/greenhouse-extensions pull request #373
Opened 2024-09-04 13:39 UTC by hodanoori

## Pull Request Details

Edit service owner

2024-09-05 11:57 UTC, TilmanHaupt reviewed
If you change between the details views the pills stay from the old detail. I would think about cleaning them. After changing the detailView. Also fixing size of the header-colum could be considered as talked in the sync.

2024-09-05 13:04 UTC, edda requested changes

2024-09-05 13:04 UTC, edda commented on heureka/ui/src/components/services/ServicesDetails.jsx
> +              <p>Are you sure you want to remove this owner?</p>
It's always better to repeat to the user what exactly is getting removed. So pass the user name to the modal and then change the text to `Are you sure you want to remove { ownerName } from owners?`

2024-09-05 13:09 UTC, edda requested changes

2024-09-05 13:09 UTC, edda commented on heureka/ui/src/components/services/ServicesDetails.jsx
> +            {showComboBox && (
When the add user combobox is shown and the user clicks on another service in the services list then the details view is updated but the combobox is still shown. This is confusing. 
Either prevent list clicks when the combobox is shown or ensure that the "edit mode", i.e. combobox is visible is reset when the user clicks on another service in the list.

2024-09-06 09:39 UTC, edda approved these changes

2024-09-06 09:40 UTC, merged