feat(helm): add OpenSearch Operator Helm chart
cloudoperators/greenhouse-extensions pull request #513
Opened 2024-11-18 09:37 UTC by joluc

# Submit a pull request

Thank you for submitting a pull request!  
To speed up the review process, please ensure that everything below
is true:

1. This is not a duplicate of an existing Plugin.
2. No existing features have been broken without good reason.
3. The Documentation has been updated to reflect your changes.
4. Tests have been added or updated to reflect your changes.
5. All tests pass.

---

Replace any ":question:" below with information about your pull request.

## Pull Request Details

Provide details about your pull request and what it adds, fixes, or changes.

This PR adds a Helm chart for the OpenSearch Operator

2025-02-21 14:32 UTC, timojohlo requested changes
Thanks for putting work into this and cool to see the progress! 
I have added some comments, let me know if you have questions :)

2025-02-21 14:32 UTC, timojohlo commented on opensearch/chart/Chart.yaml
> +    repository: https://opensearch-project.github.io/opensearch-k8s-operator/ # TODO: Move to -> oci://ghcr.io/cloudoperators/greenhouse-extensions/charts
As I understand it you will use the upstream charts? Then this will likely stay and will have the depedency from there, no?

2025-02-21 14:32 UTC, timojohlo commented on opensearch/chart/Chart.yaml
> +    repository: https://opensearch-project.github.io/opensearch-k8s-operator/ # TODO: Move to -> oci://ghcr.io/cloudoperators/greenhouse-extensions/charts
Is there another helm-chart used for the clusters? Then this repository likely needs to point to that one.

2025-02-21 14:32 UTC, timojohlo commented on opensearch/chart/templates/users/user-admin-password.yaml
> +  username: YWRtaW4= # admin (testing only)
security-wise and going forward I think it makes sense to template the secrets here and add them as a field in the plugindefinition?

2025-02-24 07:55 UTC, timojohlo requested changes

2025-02-24 08:02 UTC, timojohlo requested changes
two additional things I noticed

2025-02-24 08:48 UTC, trouaux commented
do we need chart/crds ? looks like they are all part of the archives

2025-02-24 09:55 UTC, ibakshay commented
Suggested edit:
```diff
diff --git a/.github/configs/helm-lint.yaml b/.github/configs/helm-lint.yaml
index 9a692cb..0944246 100644
--- a/.github/configs/helm-lint.yaml
+++ b/.github/configs/helm-lint.yaml
@@ -17,6 +17,7 @@ chart-dirs:
   - logshipper
   - opentelemetry
   - thanos
+  - opensearch
 chart-repos:
   - cert-manager=https://charts.jetstack.io
   - alerts=https://prometheus-community.github.io/helm-charts
@@ -24,3 +25,4 @@ chart-repos:
   - kubernetes-operations=https://cloudoperators.github.io/kubernetes-operations
   - logshipper=https://fluent.github.io/helm-charts
   - opentelemetry=https://open-telemetry.github.io/opentelemetry-helm-charts
+  - opensearch=https://opensearch-project.github.io/opensearch-k8s-operator
diff --git a/.github/configs/helm-test.yaml b/.github/configs/helm-test.yaml
index e09e065..c7b9393 100644
--- a/.github/configs/helm-test.yaml
+++ b/.github/configs/helm-test.yaml
@@ -12,8 +12,10 @@ chart-dirs:
   - plutono
   - thanos
   - opentelemetry
+  - opensearch
 chart-repos:
   - cert-manager=https://charts.jetstack.io
   - alerts=https://prometheus-community.github.io/helm-charts
   - kube-monitoring=https://prometheus-community.github.io/helm-charts
   - opentelemetry=https://open-telemetry.github.io/opentelemetry-helm-charts
+  - opensearch=https://opensearch-project.github.io/opensearch-k8s-operator

```

2025-03-06 14:58 UTC, joluc commented on opensearch/README.md
> +![OpenSearch Architecture](img/opensearch-arch.png)
Added

2025-03-06 14:58 UTC, joluc commented on opensearch/chart/Chart.yaml
> +    repository: https://opensearch-project.github.io/opensearch-k8s-operator/ # TODO: Move to -> oci://ghcr.io/cloudoperators/greenhouse-extensions/charts
Yes, removed the comment.

2025-03-06 14:58 UTC, joluc commented on opensearch/chart/Chart.yaml
> +    repository: https://opensearch-project.github.io/opensearch-k8s-operator/ # TODO: Move to -> oci://ghcr.io/cloudoperators/greenhouse-extensions/charts
It's another chart in the same repository. The URL is the same but just the folder is named `opensearch-cluster`

2025-03-06 14:58 UTC, joluc commented on opensearch/chart/values.yaml
> +owner-info:
Removed

2025-03-07 12:07 UTC, joluc commented on opensearch/chart/templates/users/user-admin-password.yaml
> +  username: YWRtaW4= # admin (testing only)
Yes, this was still from my testing. Thank you :)

2025-03-11 10:39 UTC, timojohlo requested changes
two minor points

2025-03-11 10:52 UTC, timojohlo requested changes

2025-03-11 10:52 UTC, timojohlo commented on opensearch/plugindefinition.yaml
> +  version: 2.6.0
the PluginDefinition version is decoupled from the upstream chart version. You can declare versions following the semver.org versioning

2025-03-11 10:52 UTC, timojohlo commented on opensearch/plugindefinition.yaml
> +    - default: false
the expected datatype here is string but the default value is a boolean, should be "" or filled string

2025-03-25 08:39 UTC, joluc commented on opensearch/plugindefinition.yaml
> +  version: 2.6.0
Good point. Let's start with `1.0.0`

2025-03-25 08:40 UTC, joluc commented on opensearch/plugindefinition.yaml
> +    - default: false
Yes, changed! :)

2025-03-28 11:48 UTC, joluc commented on opensearch/README.md
> +
Done! Thanks :)

2025-03-28 22:08 UTC, ibakshay approved these changes
Awesome work! LGTM 🚀

2025-03-31 07:13 UTC, IvoGoman approved these changes

2025-03-31 07:48 UTC, timojohlo approved these changes
well done!

2025-04-07 13:27 UTC, merged