Add Perses Plugin
cloudoperators/greenhouse-extensions pull request #539
Opened 2024-12-09 16:18 UTC by ibakshay

This Pull request resolves https://github.com/cloudoperators/greenhouse-extensions/issues/491

Signed-off-by: IB Akshay <akshay.iyyadurai.balasundaram@sap.com>

2024-12-10 11:02 UTC, viennaa requested changes
Thanks for providing the Perses Plugin, really looking foward seeing it in action.

Some smaller nits inline.

2024-12-10 11:02 UTC, viennaa commented on perses/plugindefinition.yaml
> +          description: "a sidecar container is deployed in the perses pod. This container watches all configmaps in the cluster and filters out the ones with a label `perses.dev/resource: true`. The
```suggestion
          description: "Deploys a sidecar container to watch all configmaps in the cluster and filters out the ones with a label `perses.dev/resource: true`. The files defined in those configmaps are written to a folder and this folder is accessed by Perses. Changes to the configmaps are continuously monitored and reflected in Perses within 10 seconds"
```

2024-12-10 11:03 UTC, viennaa commented
Also, add some tests please :).

2024-12-10 12:58 UTC, ibakshay commented on perses/img/perses-arch.png
Thanks so much. Great feedback! 
I have increased the resolution and I have also done changes to the diagram as you have suggested in 
66f1a4f57b3e14da7d236e789f666984f9e9aeed

2024-12-10 13:03 UTC, ibakshay commented on kube-monitoring/charts/values.yaml
> +    persesDatasource: false
Yes, that's correct. I thought of disabling by default in the beginning as it is not tested in the productive environments yet. However, if you see it differently, we can also enable it by default from the start. :)

2024-12-10 13:13 UTC, viennaa commented on perses/img/perses-arch.png
Please go with either upper case or lower case for `dashboards` and `datasources`

2024-12-10 13:56 UTC, ibakshay commented on perses/img/perses-arch.png
sure. fixed in 95d35902ebdd3fa5fa99ce2b2bd09295de40bbc8

2024-12-10 13:58 UTC, ibakshay commented on kube-monitoring/charts/values.yaml
> +    persesDatasource: false
cool :) fixed in 9be4aafab35fd852e562d3a41a3682b6ae23eea6

2024-12-11 07:36 UTC, ibakshay commented
> Also, add some tests please :).

Created a PR in upstream helm chart to add tests.  https://github.com/perses/helm-charts/pull/42

2024-12-11 13:43 UTC, ibakshay commented
> Also, add some tests please :).

Tests are added to the upstream Perses helm repo now :) 

### Screenshot of the tests that are run in this PR
![image](https://github.com/user-attachments/assets/c749d0e1-7b86-41c7-92a9-ca60a98c3752)

2024-12-19 12:36 UTC, richardtief commented on perses/charts/Chart.yaml
> +name: perses-plugin
The suffix `-plugin` is not required.
```suggestion
name: perses
```

2024-12-19 12:38 UTC, richardtief commented on perses/charts/values.yaml
> +  # Default values for perses.
Enter an empty dict here to indicate the expected data type.
```suggestion
  commonLabels: {}

perses:
  # Default values for perses.
```

2024-12-19 12:42 UTC, richardtief commented on perses/plugindefinition.yaml
> +          type: bool
The indentation of yaml looks a bit off. 
```suggestion
kind: PluginDefinition
metadata:
  name: perses
spec:
  version: 0.1.0
  displayName: Perses
  description: "Perses is a dashboard tooling to visualize metrics and traces produced by observability tools such as Prometheus/Thanos/Jaeger"
  docMarkDownUrl: https://raw.githubusercontent.com/cloudoperators/greenhouse-extensions/main/perses/README.md
  icon: https://raw.githubusercontent.com/cloudoperators/greenhouse-extensions/main/perses/logo.png
  helmChart:
      name: perses
      repository: oci://ghcr.io/cloudoperators/greenhouse-extensions/charts
      version: '0.7.4'
  options:
    - default: true
      description: "Deploys a sidecar container to watch all configmaps in the cluster and filters out the ones with a label `perses.dev/resource: true`. The files defined in those configmaps are written to a folder and this folder is accessed by Perses. Changes to the configmaps are continuously monitored and reflected in Perses within 10 seconds"
      name: perses.sidecar.enabled
      required: true
      type: bool
```

2025-01-08 13:18 UTC, richardtief approved these changes
Again, great work. Let's ship it!

2025-01-08 14:42 UTC, IvoGoman approved these changes
+1, for `.github/licenserc.yaml`

2025-01-08 14:49 UTC, merged